name: Auto Release Description Generator
description: Automatically generate release descriptions using AI based on git diff
inputs:
  gemini-api-key:
    description: 'The API key for the Gemini API'
    required: true
  github-token:
    description: 'GitHub token for release operations'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
  jira-ticket-url-prefix:
    description: 'JIRA ticket URL prefix (e.g., https://company.atlassian.net/browse/)'
    required: false
    default: 'https://virdocs.atlassian.net/browse/'
  ignore-files:
    description: 'Comma-separated list of files to ignore in the diff (e.g., package-lock.json,yarn.lock)'
    required: false
    default: 'package-lock.json,yarn.lock,pnpm-lock.yaml,composer.lock,Gemfile.lock,poetry.lock,Pipfile.lock'
outputs:
  description:
    description: 'The generated release description'
    value: ${{ steps.generate_description.outputs.description }}
  updated:
    description: 'Whether the release description was updated'
    value: ${{ steps.update_pr.outputs.updated }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    
    - name: Install dependencies
      shell: bash
      run: |
        npm install
      working-directory: ${{ github.action_path }}
    
    - name: Generate PR diff from GitHub
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
        IGNORE_FILES: ${{ inputs.ignore-files }}
      run: |
        # Get the PR diff directly from GitHub using gh CLI
        gh pr diff ${{ inputs.pr-number }} > pr.diff
        echo "Generated diff file with $(wc -l < pr.diff) lines"
        
        # Filter out ignored files from the diff
        if [ -n "$IGNORE_FILES" ]; then
          echo "Filtering out ignored files: $IGNORE_FILES"
          node ${{ github.action_path }}/filter_diff.js pr.diff "$IGNORE_FILES"
          echo "Filtered diff file now has $(wc -l < pr.diff) lines"
        fi
    
    - name: Generate PR description
      id: generate_description
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
        JIRA_TICKET_URL_PREFIX: ${{ inputs.jira-ticket-url-prefix }}
      run: |
        # Generate description using AI (with chunking support for large diffs)
        node ${{ github.action_path }}/generate_pr_description.js pr.diff > release_description.md
        
        # Get existing PR body to preserve all content
        gh pr view ${{ inputs.pr-number }} --json body --jq '.body' > pr_body.md
        
        # Insert the generated description into the existing PR body
        # This preserves all existing content and uses comment tags for auto-generated section
        node ${{ github.action_path }}/insert_release_description.js pr_body.md release_description.md > new_body.md
        
        # Output the description for other steps to use
        echo "description<<EOF" >> $GITHUB_OUTPUT
        cat release_description.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Update PR description
      id: update_pr
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
      run: |
        # Update PR with merged body (preserves all existing content)
        gh pr edit ${{ inputs.pr-number }} --body-file new_body.md
        echo "updated=true" >> $GITHUB_OUTPUT
        echo "Successfully updated PR #${{ inputs.pr-number }} description"
