name: "Static Analysis"
description: "Runs static analysis on the code"

inputs:
  ignored-accounts:
    description: "Comma-separated list of accounts to ignore"
    required: false
    default: "actions,VirdocsSoftware"

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Scan workflow yml files
      run: |
        echo "Running the following script: ${{ github.action_path }}/scan_github_actions.js"
        echo "With the current working directory: $(pwd)"
        node ${{ github.action_path }}/scan_github_actions.js
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        IGNORED_ACCOUNTS: ${{ inputs.ignored-accounts }}