name: "Static Analysis"
description: "Runs static analysis on the code"

inputs:
  path:
    description: "Path to the directory or file to analyze"
    required: true
    default: "."

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Scan workflow yml files
      run: |
        node ${{ github.action_path }}/scan_github_actions.js
      shell: bash
      working-directory: ${{ inputs.path }}
  