on:
    workflow_call:
        inputs:
            aws-region:
              description: "The AWS Region to deploy the AWS resources into."
              type: string
              default: us-east-1
            dev-branch:
              description: "The name of the branch used to deploy into the Dev environment."
              type: string
              default: refs/heads/develop
            uat-branch:
              description: "The name of the branch used to deploy into the UAT environment."
              type: string
              default: refs/heads/uat
            demo-branch:
              description: "The name of the branch used to deploy into the Demo environment."
              type: string
              default: refs/heads/demo
            prod-branch:
              description: "The name of the branch used to deploy into the Prod environment."
              type: string
              default: refs/heads/main
        secrets:
            dev-aws-access-key-id:
              description: "A valid AWS Access Key ID for the Dev AWS account deployments and interactions."
              required: true
            dev-aws-secret-access-key:
              description: "A valid AWS Secret Access Key for the Dev AWS account deployments and interactions."
              required: true
            uat-aws-access-key-id:
              description: "A valid AWS Access Key ID for the UAT AWS account deployments and interactions."
              required: true
            uat-aws-secret-access-key:
              description: "A valid AWS Secret Access Key for the UAT AWS account deployments and interactions."
              required: true
            demo-aws-access-key-id:
              description: "A valid AWS Access Key ID for the Demo AWS account deployments and interactions."
              required: true
            demo-aws-secret-access-key:
              description: "A valid AWS Secret Access Key for the Demo AWS account deployments and interactions."
              required: true
            prod-aws-access-key-id:
              description: "A valid AWS Access Key ID for the Prod AWS account deployments and interactions."
              required: true
            prod-aws-secret-access-key:
              description: "A valid AWS Secret Access Key for the Prod AWS account deployments and interactions."
              required: true

jobs:
    lint-cloudformation:
        runs-on: ubuntu-latest

        steps:
          - name: Configure AWS credentials Dev
            if: github.ref == ${{ inputs.dev-branch }}
            uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
            with:
              aws-access-key-id: ${{ secrets.dev-aws-access-key-id }}
              aws-secret-access-key: ${{ secrets.dev-aws-secret-access-key }}
              aws-region: ${{ inputs.aws-region }}
          - name: Configure AWS credentials UAT
            if: github.ref == ${{ inputs.uat-branch }}
            uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
            with:
              aws-access-key-id: ${{ secrets.uat-aws-access-key-id }}
              aws-secret-access-key: ${{ secrets.uat-aws-secret-access-key }}
              aws-region: ${{ inputs.aws-region }}
          - name: Configure AWS credentials Demo
            if: github.ref == ${{ inputs.demo-branch }}
            uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
            with:
              aws-access-key-id: ${{ secrets.demo-aws-access-key-id }}
              aws-secret-access-key: ${{ secrets.demo-aws-secret-access-key }}
              aws-region: ${{ inputs.aws-region }}
          - name: Configure AWS credentials Prod
            if: github.ref == ${{ inputs.prod-branch }}
            uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
            with:
              aws-access-key-id: ${{ secrets.prod-aws-access-key-id }}
              aws-secret-access-key: ${{ secrets.prod-aws-secret-access-key }}
              aws-region: ${{ inputs.aws-region }}
