on:
  workflow_call:
    inputs:
      cfn-template-file-1:
        description: "The path to a CloudFormation template .yml or .yaml file to be linted."
        required: true
        type: string
      cfn-template-file-2:
        description: "(Optional) The path to another CloudFormation template .yml or .yaml file to be linted."
        required: false
        type: string
        default: ""
    secrets:
      env-github-token:
        description: "A valid GitHub token to be used by the action."
        required: true

jobs:
  verify-cloudformation-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Version
        run: |
          echo 'lint-cfn v1.1.0'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup CloudFormation Formatter
        run: |
          gh release download --repo aws-cloudformation/rain --pattern "*_linux-amd64.zip" --output "rain.zip"
          unzip -j "rain.zip" "*/rain"
        env:
          GH_TOKEN: ${{ secrets.env-github-token }}

      - name: Verify with CloudFormation Formatter
        run: |
          ./rain fmt --verify ${{ inputs.cfn-template-file-1 }} ${{ inputs.cfn-template-file-2 }}

      - name: Advice for Addressing Action Failure - CloudFormation Formatting
        if: failure()
        run: |
          echo 'Your build failed due to your CloudFormation template file(s) requiring edits to pass our required formatting rules.'
          echo 'Please review the previous "Verify with CloudFormation Formatter" step to see which file(s) need to be formatted.'
          echo 'You need to format the CloudFormation file(s) using the autoformatter before commiting your change.'
          echo 'Consult the ReadMe for guidance https://github.com/VirdocsSoftware/github-actions/tree/main#cfn-formatting-rain'

  verify-cloudformation-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Version
        run: |
          echo 'lint-cfn v1.1.0'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup CloudFormation Linter
        uses: scottbrenner/cfn-lint-action@v2

      - name: Verify with CloudFormation Linter
        run: |
          cfn-lint --version
          echo 'Running CFN Linter on ${{ inputs.cfn-template-file-1 }} ${{ inputs.cfn-template-file-2 }}'
          cfn-lint -t ${{ inputs.cfn-template-file-1 }} ${{ inputs.cfn-template-file-2 }}

      - name: Advice for Addressing Action Failure - CloudFormation Linting
        if: failure()
        run: |
          echo 'Your build failed due to your CloudFormation template file(s) requiring edits to pass our required linting rules.'
          echo 'Please review the previous "Verify with CloudFormation Linter" step for more explicit failure reasoning.'
          echo 'You need to correct the linting warnings and errors before commiting your change.'
          echo 'Consult the ReadMe for guidance https://github.com/VirdocsSoftware/github-actions/tree/main#cfn-linting-cfn-lint'
