name: Tag Tickets Test

on:
  push:
    branches:
        - develop
        - uat
        - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    tag-jira-release:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
          - name: create prompt
            id: create_prompt
            run: |
              DIFF="$(git log --pretty=format:'%s' origin/main..HEAD)"
              LLM_PROMPT_PREFIX="Create a fun release description in 100 characters or less in one line without identifiers for the following data:
              "
              LLM_PROMPT="$LLM_PROMPT_PREFIX$DIFF"
              echo "$LLM_PROMPT"
              # Use a delimiter to properly handle the multi-line value
              echo "LLM_PROMPT<<EOF" >> $GITHUB_OUTPUT
              echo "$LLM_PROMPT" >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT
          - uses: ./.github/actions/llm-action
            id: llm_action
            with:
              gemini-api-key: ${{ secrets.LLM_API_TOKEN }}
              prompt: ${{ steps.create_prompt.outputs.LLM_PROMPT }}
          - name: Debug
            run: echo '${{ steps.llm_action.outputs.response }}'
          - uses: ./.github/actions/tag-jira-release
            with:
              description: ${{ steps.llm_action.outputs.response }}
              target-branch: 'origin/main'
              jira-token: ${{ secrets.JIRA_API }}
              jira-email: ${{ secrets.JIRA_API_CREDENTIALS }}
              jira-domain: 'virdocs.atlassian.net'
              dry-run: 'false'