on:
  workflow_call:
    inputs:
      target-branch:
        description: "The target branch to tag the release."
        type: string
        required: true
      jira-domain:
        description: "The JIRA domain to tag the release."
        type: string
        required: true
    secrets:
      LLM_API_TOKEN:
        description: "A valid LLM API token to be used by the action."
        required: true
      JIRA_API:
        description: "A valid JIRA API token to be used by the action."
        required: true
      JIRA_API_CREDENTIALS:
        description: "A valid JIRA API email to be used by the action."
        required: true

jobs:
  tag-jira-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: create prompt
        id: create_prompt
        run: |
          DIFF="$(git log --pretty=format:'%s' origin/main..HEAD)"
          LLM_PROMPT_PREFIX="Create a fun release description in 100 characters or less in one line without identifiers for the following data:
          "
          LLM_PROMPT="$LLM_PROMPT_PREFIX$DIFF"
          echo "$LLM_PROMPT"
          # Use a delimiter to properly handle the multi-line value
          echo "LLM_PROMPT<<EOF" >> $GITHUB_OUTPUT
          echo "$LLM_PROMPT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - uses: VirdocsSoftware/github-actions/.github/actions/llm@main
        id: llm_action
        with:
          gemini-api-key: ${{ secrets.LLM_API_TOKEN }}
          prompt: ${{ steps.create_prompt.outputs.LLM_PROMPT }}
      - name: Debug
        run: echo '${{ steps.llm_action.outputs.response }}'
      - uses: VirdocsSoftware/github-actions/.github/actions/tag-jira-release@main
        with:
          description: ${{ steps.llm_action.outputs.response }}
          target-branch: ${{ inputs.target-branch }}
          jira-token: ${{ secrets.JIRA_API }}
          jira-email: ${{ secrets.JIRA_API_CREDENTIALS }}
          jira-domain: ${{ inputs.jira-domain }}
          dry-run: 'false'