name: Validate PR

on:
  workflow_call:
    inputs:
      pr_title:
        description: "The title of the pull request."
        type: string
        required: true
      pr_branch:
        description: "The branch name of the pull request."
        type: string
        required: true
      latest_release:
        description: "The latest release version."
        type: string
        required: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Package
        run: |
          PACKAGE_VERSION=$(cat package.json | jq -r '.version')
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
      - name: Validate PR title and branch
        uses: VirdocsSoftware/github-actions/.github/actions/validate-pr@feat/CORE-1611-PR-hygiene-check-workflow
        with:
          pr_title: ${{ github.event.inputs.pr_title }}
          pr_branch: ${{ github.event.inputs.pr_branch }}
          latest_release: ${{ github.event.inputs.latest_release }}
          package_version: ${{ github.env.PACKAGE_VERSION }}
          target_branch: ${{ github.event.inputs.target_branch }}

