name: 'wizcli-scanner'
on:
  workflow_call:

jobs:
  wizcli-scan:
    name: 'Wizcli Scan'
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: "." # Set the relative path in the repo to scan
      TIMEOUT: 60s

    defaults:
      run:
        shell: bash

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download Wiz CLI
      run: curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

    - name: Authenticate to Wiz
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"

    - name: Run wiz CLI IaC scan
      run: ./wizcli iac scan --path $SCAN_PATH --timeout $TIMEOUT

    - name: Run wiz CLI directory scan
      run: ./wizcli dir scan --path $SCAN_PATH --timeout $TIMEOUT --sensitive-data
